### ISSUE TITLE
ไม่สามารถติดตั้งตาม readme.md ได้ครับ

### ISSUE THREAD

**Issue by naruepat** [kanomtang/MovieTicketReact#1]
![screen shot 2561-06-05 at 16 00 08](https://user-images.githubusercontent.com/5475736/40966034-9573e65c-68d9-11e8-80c9-5dd53f691c1a.png)

**Comment by kanomtang** [comment]
ลองกด pull ดูครับ ผมพึ่งอัพเดต  package.jsonไป สักครู่

**Comment by kanomtang** [comment]
ขอโทษด้วยนะครับ ที่เขียน readme ไม่ละเอียด ผมลืมให้พิม npm install ด้วยครับ รบกวนทำตาม  readme อีกครั้งด้วยนะครับ หากยังมีปัญหารบกวน screencapture มาให้ดูด้วย

**Comment by naruepat** [comment]
ได้ครับผม

**Comment by kanomtang** [comment]
เป็นอย่างไรมั้งครับ

**Comment by naruepat** [comment]
สามารถติดตั้งได้แล้วครับ
