### ISSUE TITLE
ต้องการให้ลองเอาขึ้น online 

### ISSUE THREAD

**Issue by naruepat** [kanomtang/MovieTicketReact#2]
ต้องการให้ลองเอาขึ้น online ที่ไหนก็ได้ และอัพเดท Readme.md โดยนำลิงค์มาแปะครับ

**Comment by kanomtang** [comment]
เสร็จแล้วครับ 
https://kanomtang.github.io/MovieTicketReact/ 
พร้อมทั้ง แก้ไข ใน readme.mdแล้วครับ
